[package]
name = "twitter-analyzer"
version = "0.1.0"
authors = ["Mike Kaliman <kaliman.mike@gmail.com>"]
edition = "2018"


[dependencies]
egg-mode = "0.15.0"
tokio = {version = "0.2", features = ["full"]}
serde_json = "1.0"
serde = "1.0"
clap = "2"
regex = "1.4.2"
chrono = "0.4"
walkdir = "2.3"