[package]
name = "twitter-bot"
version = "0.1.0"
authors = ["Mike Kaliman <kaliman.mike@gmail.com>"]
edition = "2018"


[dependencies]
egg-mode = "0.15.0"
tokio = "0.2.22"
serde_json = "1.0.57"
serde = "1.0.116"
clap = "2"
regex = "1.3.9"